# Generated by Django 4.2.5 on 2023-10-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_carmodel_option_carmodel_year'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='my_garage',
            field=models.ManyToManyField(blank=True, related_name='car_model', to='car_app.carmodel'),
        ),
    ]
