# Generated by Django 4.2.5 on 2023-10-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='option',
            field=models.CharField(default='none'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
